### ISSUE TITLE
Apple TV 4K does not switch off BRAVIA via HDMI-CEC

### ISSUE THREAD

**Issue by CiNcH83** [CiNcH83/bravia_atv2#86] opened 2020-11-19 12:12 UTC
As of Pie, Apple TV 4K does not switch off the BRAVIA via HDMI-CEC anymore when putting the Apple TV 4K into standby.

This is what the configuration looks like here:
```
 __________________          ____________
| BRAVIA     HDMI1 |_       |            |
| XF9005     HDMI2 |________| AppleTV 4K |
|        HDMI3/ARC |____    |____________|
|            HDMI4 |_   |    ____________
|__________________|    |___|   Teufel   |
                            | Cinebar 52 |
                            |____________|
```

When switching off the Apple TV 4K, the Cinebar is being switched off, just to be turned back on 1-2s later. BRAVIA stays on.

Looks like another CEC timing issue, just like #8 .

**Comment by vincentwslee** [comment] 2020-11-19 17:35
I can confirm this is now happening for me after the Android 9 update (6.7140). My Apple TV 4K is plugged into a Denon X3500H which is plugged into the X900F's HDMI 3 input. Previously the entire chain would power off when "Sleep all connected devices" was selected in the Apple TV.

A few others have reported this issue in this thread as well: 

https://www.reddit.com/r/bravia/comments/js4i4s/android_9_pie_for_20162019_bravias_available_now/

Thanks for keeping this up to date!

**Comment by Morac2** [comment] 2020-11-23 06:08
I’m not 100% certain, but I think the TV may power off and immediately turn back on again.  The reason I think so, is that when putting my Apple TV 4K into standby my Onkyo receiver powers off and then powers back on a few seconds later, which only usually occurs when the TV powers on.  Something odd definitely occurs though as the HDMI input changes from HDMI 2, where I have my Apple TV 4K plugged into to either HDMI 3/ARC or occasionally HDMI 4.  I think that depends on what was last used. 

I reported this to Sony, but they just said to do a factory reset, which others have reported does not solve the issue. 

https://us.community.sony.com/s/feed/0D54O00006gHBToSAO?language=en_US

**Comment by Morac2** [comment] 2020-11-27 14:09
I tested a Roku Premiere and it can turn off my 930e, though it doesn’t turn off the audio receiver.  As such I wonder if the problem is the TV is intercepting the command to power off my receiver and turning the TV back on.

**Comment by delize** [comment] 2020-12-16 00:17
Well coming back to this, I had a similar issue happen to me yesterday with the nVidia Shield with the TV not staying turned off and immediately turning back on after putting it to sleep/poweroff. Now my TV is bootlooping and won't turn back on at all.

**Comment by brbigs** [comment] 2020-12-21 23:30
Same issue for me. X900F and Apple TV 4K worked fine for 2 years. Now the Apple TV can’t put the X900F to sleep. I’ve tried several comibinations of inputs, cables, factory reset the X900F and Apple TV... none of it works. Frustrating to say the least.

**Comment by stefanbiba** [comment] 2021-01-19 16:33
Same here. X900E connected to ATV4k via Yamaha Receiver. Everything turn off when I put ATV in sleep mode but TV remains on and so the AV-Receiver is also turning on again after a few seconds. Why, Sony/Google?

**Comment by gittes** [comment] 2021-01-20 05:10
I can confirm this with the ATV4K and my Sony XBR-65A8F. Also had this nice convenience of the ATV4K could turn off the TV for two years, now I have to also use my Sony remote to turn off the TV after putting the ATV4K to sleep. 

Even worse, when I use the Sony remote too quickly to turn off the TV, the TV turns back on AGAIN, and I have to turn it off a second time! Definitely HDMI-CEC timing issues.

The mentioned Sony link provided by @Morac2 has been updated and support gave a standard acknowledgment that they are aware of the problem and are working on it, but no further details.

Annoyed.

**Comment by stefanbiba** [comment] 2021-01-20 09:20
> I can confirm this with the ATV4K and my Sony XBR-65A8F. Also had this nice convenience of the ATV4K could turn off the TV for two years, now I have to also use my Sony remote to turn off the TV after putting the ATV4K to sleep.
> 
> Even worse, when I use the Sony remote too quickly to turn off the TV, the TV turns back on AGAIN, and I have to turn it off a second time! Definitely HDMI-CEC timing issues.
> 
> The mentioned Sony link provided by @Morac2 has been updated and support gave a standard acknowledgment that they are aware of the problem and are working on it, but no further details.
> 
> Annoyed.

I also noticed that yesterday when I turned off the TV too fast. Hope they are launching a fix soon. Really!

**Comment by simnew** [comment] 2021-02-01 15:43
Does anyone know if Sony are looking into this or if it has been registered formally as a serious bug ?

**Comment by brbigs** [comment] 2021-02-01 15:52
> Does anyone know if Sony are looking into this or if it has been registered formally as a serious bug ?

It has been reported on the Sony community forums and a Sony employee (RomeoP) has responded. 
[link](https://ap.community.sony.com/s/question/0D54O00006gHBToSAO/after-v67140-update-xbr55x930e-devices-wont-power-off-tv)

**Comment by arbyter** [comment] 2021-03-07 20:46
According to a recent [post](https://us.community.sony.com/s/feed/0D54O00006gHBToSAO?language=en_US) Form Feb 2021 in this thread Sony is about to ship an update in mid April 2021.

**Comment by bdhjiajia** [comment] 2021-03-10 00:58
PKG6.7140.****CNA，in China
55X9000F,Apple TV 4K does not switch off the BRAVIA via HDMI-CEC anymore when putting the Apple TV 4K into standby.

**Comment by d19dotca** [comment] 2021-03-28 23:12
My Sony TV was just updated this morning and have spent hours troubleshooting this - am thankful to have found this thread. Happy to know it's a known issue at Sony already and that a fix is incoming. Just really frustrated at how much time was lost as a result, especially considering how long it's been since the TV update was released. 

My setup: Apple TV 4K --> Sony HT-Z9F soundbar --> Sony XBR85X900F TV

Prior to the latest Sony update which brought Android 9.0, I would be able to power off / sleep the Apple TV which in-turn powered off the soundbar which in-turn powered off the TV. Since the update, sleeping the Apple TV temporarily powers down the soundbar, the TV remains on and switches to the TV speakers instead with no input source, and a minute later my soundbar powers itself back on (presumably because of the TV).

Here's hoping for a fix soon. Definitely frustrating to have to use two remotes now. 

For continuity sake, I'm including a couple of references leading up to me stumbling across this issue listed in this GitHub repo:

- https://piunikaweb.com/2021/03/23/sony-bravia-sync-hdmi-cec-not-working-with-apple-tv/
- https://twitter.com/SonySupportUSA/status/1373403262439727111
- https://www.reddit.com/r/bravia/comments/jxtzod/sony_x900f_cec_issues_devices_not_putting_tv_in/

**Comment by gtg465x** [comment] 2021-05-20 14:55
I think Sony forgot about us.

**Comment by mbehrooz** [comment] 2021-05-23 00:47
Just wanted to sat that I was fully enjoying my Sony TV but just because of this treatment, of making a 2018 TV painful to use, I won't be purchasing another Sony TV ever. This should take a week to hot fix, not a year. Shame on you all Sony.

**Comment by vertexdigital** [comment] 2021-05-24 03:07
Is there really no further update for this yet? It's been 6 months now. This will definitely be my last Sony TV ever, ridiculous.

**Comment by mk26** [comment] 2021-05-25 21:47
This issue has been finally fixed with today's update (v6.7165). Just installed it on my A8G. I had to do it via USB as it wasn't available OTA yet.

https://www.sony.com/electronics/support/oled-tvs-android-a8g_ag8-series/xbr-65a8g/software/00262031

**Comment by d19dotca** [comment] 2021-05-25 22:54
> This issue has been finally fixed with today's update (v6.7165). Just installed it on my A8G. I had to do it via USB as it wasn't available OTA yet.

Awesome news, thanks for sharing! I'd likely have not found out about the new update if it weren't for that. I'm downloading the update now to my USB to manually update. Hopefully all goes well. 🤞

**Comment by vertexdigital** [comment] 2021-05-25 23:21
Thanks for the update. Nothing released yet for my TV (X9000E) so hopefully something pops up soon

**Comment by spikenheimer** [comment] 2021-05-25 23:26
in the last hour i downloaded the manual update file linked above and applied it to my 900E and my 900F and i can also confirm at least the CEC power off works again.  (like many i also disabled auto update) 
i also noticed auto update did not show this update yet, and the software update download page implies that it can take a while (i read it as days/weeks) for updates to appear in the auto update channel…

**Closed** 2021-05-26 04:49 UTC
Labels: Apple TV 4K, HDMI-CEC, Pie

**Comment by gtg465x** [comment] 2021-05-28 17:16
Uh oh. This update seemed to fix the CEC issue at first (my Apple TV 4K finally started turning off my X900F again), but suddenly today it's back to not working again. I haven't updated the TV, although I did install an update for my HDFury Arcana the other day, so I'm not sure if it's related to that.

**Comment by Morac2** [comment] 2021-05-28 17:29
For me it partially works.  My Sony 930E and Onkyo AVR turn off, but then a few seconds later the Onkyo turns back on (like the TV turned it on).  The TV stays off though.  The AVR turns itself off after about 15 minutes since there's no input.

**Comment by reddoxster** [comment] 2021-05-30 05:36
Unfortunately it doesn't list Asia models - mine's KD-659000f. 
I even bought the new apple tv remote with a dedicated power button - didn't work! Looks like it isn't using IR to switch off.

A workaround I use that may help others is:
- Buy the new apple tv remote
- Remap the mute button the new apple remote to the TV's IR power off button

**Comment by vertexdigital** [comment] 2021-05-30 23:13
The update still isn't available in Asia Pacific, however, I managed to find out a direct download by piecing together the format for the Asia Pacific URL's along with the new firmware from other countries:

https://tv.update.sony.net/OND/2019/as/main/PS210692/sony_dtvota_2016_1607165100_paa_auth.zip

Tested this on my X9000E and it's all working perfectly, including the CEC fix.

**Comment by reubenbijl** [comment] 2021-06-15 00:09
> The update still isn't available in Asia Pacific, however, I managed to find out a direct download by piecing together the format for the Asia Pacific URL's along with the new firmware from other countries:
> 
> https://tv.update.sony.net/OND/2019/as/main/PS210692/sony_dtvota_2016_1607165100_paa_auth.zip
> 
> Tested this on my X9000E and it's all working perfectly, including the CEC fix.

Nice job, how did you work out the ID for 'PS210692'?

**Comment by vertexdigital** [comment] 2021-06-15 00:30
> > The update still isn't available in Asia Pacific, however, I managed to find out a direct download by piecing together the format for the Asia Pacific URL's along with the new firmware from other countries:
> > https://tv.update.sony.net/OND/2019/as/main/PS210692/sony_dtvota_2016_1607165100_paa_auth.zip
> > Tested this on my X9000E and it's all working perfectly, including the CEC fix.
> 
> Nice job, how did you work out the ID for 'PS210692'?

Build 210686 didn't work (the build that is available for the US), so I simply tried a sequence of numbers with a higher build number and build 210692 worked for the Asia Pacific Regions (EU was build 210693 for reference).

**Comment by k0a8t1o6** [comment] 2021-06-16 02:48
> > > The update still isn't available in Asia Pacific, however, I managed to find out a direct download by piecing together the format for the Asia Pacific URL's along with the new firmware from other countries:
> > > https://tv.update.sony.net/OND/2019/as/main/PS210692/sony_dtvota_2016_1607165100_paa_auth.zip
> > > Tested this on my X9000E and it's all working perfectly, including the CEC fix.
> > 
> > 
> > Nice job, how did you work out the ID for 'PS210692'?
> 
> Build 210686 didn't work (the build that is available for the US), so I simply tried a sequence of numbers with a higher build number and build 210692 worked for the Asia Pacific Regions (EU was build 210693 for reference).

Great work, I actually hoped for the fix with the build. But my Bravia 49X9000F did not accept it. Possibly Japan uses another build?

**Comment by walterwhip** [comment] 2021-06-18 09:10
> The update still isn't available in Asia Pacific, however, I managed to find out a direct download by piecing together the format for the Asia Pacific URL's along with the new firmware from other countries:
> 
> https://tv.update.sony.net/OND/2019/as/main/PS210692/sony_dtvota_2016_1607165100_paa_auth.zip
> 
> Tested this on my X9000E and it's all working perfectly, including the CEC fix.

I just completed this on a KD-65X7500F in Australia. Works a treat! no issues what so ever. Thanks!
(Downloaded to USB FAT32 - Pressed the help button - then updates - the tv then searched the USB and uploaded the download - tv then executed.)

**Comment by vertexdigital** [comment] 2021-06-22 01:18
> Great work, I actually hoped for the fix with the build. But my Bravia KJ-49X9000F did not accept it. Possibly Japan uses another build(not surprising)?

It looks like Japan is separate to the Asia Pacific updates, and I couldn't seem to locate a newer update for it as the format is quite different compared to all other regions

**Comment by k0a8t1o6** [comment] 2021-06-22 02:15
> > Great work, I actually hoped for the fix with the build. But my Bravia KJ-49X9000F did not accept it. Possibly Japan uses another build(not surprising)?
> 
> It looks like Japan is separate to the Asia Pacific updates, and I couldn't seem to locate a newer update for it as the format is quite different compared to all other regions

Thanks for your effort, @vertexdigital . I'd need to wait for an update from the customer support, I guess.

**Comment by WhyMe777** [comment] 2021-07-31 09:39
> Thanks for the update. Nothing released yet for my TV (X9000E) so hopefully something pops up soon

Look again. I have the update since it was released on my X900E.

**Comment by vertexdigital** [comment] 2021-08-01 23:56
> Look again. I have the update since it was released on my X900E.

Still not available for the X9000E (the Australian models use 0000's instead of 000's in the model name) last update is still showing as 02/12/2020. I'm glad I was able to manually find the update a few months ago...

**Comment by vertexdigital** [comment] 2021-08-04 23:50
And it's finally available as of yesterday for Australia, using the exact same build I linked to a few months ago :)

**Comment by jasonlieberman** [comment] 2021-09-04 13:52
It was working for a few months and now having the same problem again! TV won't turn on or off with the Apple TV.
